/**:
  ros__parameters:
    sync_cameras: ['ego_view']
    standalone_cameras: ['stereo_view']
    zmq_port: 5555
    standalone_zmq_port: 5558
    ego_view:
      topic: '/zed/zed_node/rgb/color/rect/image'
      quality: 85
      width: 640
      height: 480
    stereo_view:
      topic: '/zed/zed_node/stereo/color/rect/image'
      quality: 80
